### ISSUE TITLE
Unable to Open Console in LogViewer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anb0s/LogViewer#65]
```
What steps will reproduce the problem?
1. Lauch a Java project in Eclipse Indigo Service Release 1
2. Click on Open with Log Viewer

What is the expected output? What do you see instead?
Expect seeing output in Logviewer
Instead : WARNING: resource 
org.eclipse.debug.internal.ui.views.console.ProcessConsole\appTest [Java 
Application] C:\Program Files (x86)\Java\jre6\bin\javaw.exe (19 avr. 2012 
16:14:21) (temporarily) not available ...

What version of the product are you using? On what operating system?
0.9.8.3

Please provide any additional information below.

```

Original issue reported on code.google.com by `alexis.g...@gmail.com` on 19 Apr 2012 at 2:18

**Comment by gianghnd** [comment]
Same problem on win 7/64
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

WARNING: resource org.eclipse.debug.internal.ui.views.console.ProcessConsole\xstore (WKI) [Java Application] C:\Program Files\Java\jdk1.7.0_75\bin\javaw.exe (Aug 20, 2016, 5:15:29 PM) (temporarily) not available ...

**Comment by anb0s** [comment]
fixed
