### ISSUE TITLE
"Clean log" button

### ISSUE THREAD

**Issue by ramonamorea** [anb0s/LogViewer#88]
**"Clean log" button**

...

**Hello, I was wondering if you could a simple button named something like Clean Log, which deletes all the content in the log file (or at least cleans, deletes the visible logs in the Log View**

**How-To-Reproduce**
I am working on a big project which generates a lot of logging. It's easier for me to see the latest logs if, before I launch an action for which I want to see the logs - I first clear all previous logging. I do this now with Select All -> Delete (from keyboard). But it would be much more easier to have a button which clears all visible logs.

- Plugin version: 0.9.8.8
- Eclipse Version: Eclipse Neon.3 (release 4.6.3)
- Java Version: version 8 update 1.5.1
- Operating System Version: Windows 8.1 Pro

**Comment by anb0s** [comment]
Thanks, for the request, it looks like #34

**Comment by anb0s** [comment]
or like #46 ? no truncate but just clear the console...

**Comment by anb0s** [comment]
I'm not working on this plugin now, but will look if i can improve it in future, help (PR) is welcome...

**Comment by ramonamorea** [comment]
Thank you for your reply!
Yes, like #46 
My apologies for not seing that open issue before opening this one.
I'll see how can I help with a PR

**Comment by anb0s** [comment]
done master by @hufoAA, Thanks!

Available with #92
